"use client"
import {useState} from "react"
import Link from "next/link"
import {NATIVE_REPLAYS} from "@/lib/colosseum/native-replays"
import {Trophy} from "lucide-react"
import {useGame} from "@/lib/colosseum/game-store"
import {PUBLIC_DATA} from "@/lib/colosseum/public-trials-data"
import {CONTENDERS,getContender} from "@/lib/colosseum/characters"
import {CHALLENGES} from "@/lib/colosseum/challenges"
import {modelTitle} from "@/lib/colosseum/models"
import {ContenderPortrait} from "@/components/colosseum/contender-portrait"
export default function HallOfFame(){const game=useGame(),[challenge,setChallenge]=useState('all');const records=PUBLIC_DATA.valid.filter(e=>challenge==='all'||e.trial.challengeId===challenge)
 return <div className="page-shell hall-of-fame"><header className="page-heading"><p className="eyebrow">THE HALL OF FAME</p><h1>Evidence earns a place.</h1><p>A trophy chamber for proof. A journal for your journey. Each has its own meaning.</p></header><div className="trophy-arch" aria-hidden><span>✦</span><Trophy size={64}/><span>✦</span></div><div className="hall-categories"><section><p className="eyebrow">VERIFIED PUBLIC RESULTS</p><h2>The evidence chamber</h2><label>Challenge<select aria-label="Hall challenge" value={challenge} onChange={e=>setChallenge(e.target.value)}><option value="all">All available challenges</option>{CHALLENGES.filter(c=>c.available).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{NATIVE_REPLAYS.map(r=><article className="published-native-result" key={r.id}><h3>{r.entry.label}</h3><p>{r.entry.modelArtifact.backend} · Q8_0 · original math.warmup v1</p><p>{r.check.passed?"Checker accepted the final answer":"Checker rejected the final-answer format"}</p><Link href="/battle-archive">Inspect complete evidence →</Link></article>)}{records.length?records.map(e=>{const c=getContender(e.trial.contenderId);return <article key={e.trial.id}>{c&&<ContenderPortrait contender={c}/>}<h3>{c?modelTitle(c):e.trial.modelId}</h3><p>{e.trial.correct?'Checker accepted':'Checker rejected'} · {e.trial.modelId}</p><Link href="/battle-archive">Inspect evidence →</Link></article>}):<div className="honest-podium"><Trophy size={35} aria-hidden/><h3>The podium awaits its evidence.</h3><p>No comparable baseline public rankings have been published. Individual CPU captures use different configurations. No worldwide ranks or intelligence scores are invented.</p></div>}</section><section><p className="eyebrow">YOUR JOURNEY · PERSONAL</p><h2>Discoveries worth keeping</h2>{game.events.filter(e=>['mutation_sealed','mission_completed','practice_completed','battle_completed'].includes(e.type)).slice(0,6).map(e=><article className="personal-banner" key={e.id}><span aria-hidden>✧</span><div><strong>{e.title}</strong><small>{e.subject} · local activity</small></div></article>)}{!game.events.length&&<p>Your first mission, experiment, or practice challenge will appear here.</p>}<Link href="/journal" className="text-link">Open your adventure journal →</Link><p className="compact-note">Player progress is separate from measured AI performance. Device-local records are not global achievements.</p></section><section><p className="eyebrow">UNRANKED MODELS</p><h2>Every contender starts here.</h2><div className="hall-unranked">{CONTENDERS.filter(c=>!records.some(e=>e.trial.contenderId===c.id)).map(c=><div key={c.id}><ContenderPortrait contender={c} size="sm"/><strong>{modelTitle(c)}</strong><small>{c.name} · no public ranking</small></div>)}</div></section></div><Link href="/#trial-heading" className="action primary">Return to the Arena</Link></div>
}
