"use client"
import {useEffect,useState} from "react"
import Link from "next/link"
import {Trophy} from "lucide-react"
import {loadEvidence} from "@/lib/colosseum/evidence"
import {PUBLIC_DATA} from "@/lib/colosseum/public-trials-data"
import {toEvidenceEntry,validatePublicTrial,evidenceToCandidate} from "@/lib/colosseum/public-trials"
import {CHALLENGES} from "@/lib/colosseum/challenges"
import {CONTENDERS} from "@/lib/colosseum/characters"
import {ContenderPortrait} from "@/components/colosseum/contender-portrait"
export default function LeaderboardsPage(){const [personal,setPersonal]=useState<ReturnType<typeof loadEvidence>>([]),[scope,setScope]=useState("public"),[challenge,setChallenge]=useState(CHALLENGES[0].id),[model,setModel]=useState("")
 useEffect(()=>setPersonal(loadEvidence()),[])
 const entries=(scope==="public"?PUBLIC_DATA.valid.map(toEvidenceEntry):personal).filter(e=>e.challengeId===challenge&&(!model||e.contenderId===model)&&!e.skillId&&(!e.status||e.status==="complete")&&validatePublicTrial(evidenceToCandidate(e)).ok)
 const rows=CONTENDERS.map(c=>{const records=entries.filter(e=>e.contenderId===c.id);return{champion:c,n:records.length,correct:records.filter(e=>e.correct).length}}).filter(r=>r.n).sort((a,b)=>b.correct/b.n-a.correct/a.n)
 return <div className="page-shell"><header className="page-heading"><p className="eyebrow">THE ARCADE HALL OF FAME</p><h1>Evidence earns a place.</h1><p>Results for one challenge at one checker version. Public recorded evidence and personal browser history stay separate. No universal intelligence score.</p></header><div className="button-row"><label className="text-xs">Ranking source<select aria-label="Ranking source" value={scope} onChange={e=>setScope(e.target.value)}><option value="public">Public recorded evidence</option><option value="personal">Personal browser history</option></select></label><label className="text-xs">Challenge<select aria-label="Leaderboard challenge" value={challenge} onChange={e=>setChallenge(e.target.value)}>{CHALLENGES.filter(c=>c.available).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs">Model<select aria-label="Leaderboard model" value={model} onChange={e=>setModel(e.target.value)}><option value="">All champions</option>{CONTENDERS.map(c=><option key={c.id} value={c.id}>{c.family} · {c.name}</option>)}</select></label></div>{rows.length<3?<div className="hall-empty"><div className="trophy-stage" aria-hidden="true">{[1,2,3].map(i=><div className="trophy-plinth" key={i}><Trophy size={32}/></div>)}</div><h2 className="font-display text-3xl">The podium awaits its evidence.</h2><p className="text-sm mt-4">{rows.length?"Fewer than three comparable contenders. No podium assigned.":"No valid comparable records in this view. No ranks or scores have been invented."}</p></div>:<div className="trophy-stage">{rows.slice(0,3).map((r,i)=><div className="trophy-plinth" key={r.champion.id}><ContenderPortrait contender={r.champion} size="sm"/><span className="text-xs">#{i+1} · {r.champion.name}</span></div>)}</div>}{rows.length>0&&<div className="record-list">{rows.map(r=><article key={r.champion.id} className="vault-record"><header><ContenderPortrait contender={r.champion} size="sm"/><div><h2>{r.champion.name}</h2><small>{r.champion.modelId}</small></div><div className="ml-auto text-right"><strong>{Math.round(r.correct/r.n*100)}% correct</strong><p className="text-xs">n={r.n} · {r.correct} accepted answers</p></div></header><Link className="text-xs underline mt-4 inline-block" href="/battle-archive">Inspect underlying trial evidence</Link></article>)}</div>}<p className="notice">Small samples do not establish model superiority. Client-controlled records are not independently attested. Legacy records with skill modifiers are excluded from this baseline view; complete build rankings await configuration-aware recordings.</p><Link className="action" href="/developers">Recover and validate recordings</Link></div>
}
