import {describe,it,expect} from "vitest"
import {createBuild,cloneBuild,equipSkill,saveBuildEdit,composeInstructions,configFingerprint,validateBuild} from "@/lib/colosseum/builds"
import {exportBuild,importBuild} from "@/lib/colosseum/build-store"
describe("complete saved configurations",()=>{
 it("normalizes instruction order consistently with the fingerprint",()=>{const b=createBuild("capybara-sage","Sage");const a={...b.config,soul:"Be precise",skillIds:["proof-scaffolding","socratic-inquiry"]};const z={...a,skillIds:a.skillIds.slice().reverse()};expect(configFingerprint(a)).toBe(configFingerprint(z));expect(composeInstructions(a)).toBe(composeInstructions(z));expect(composeInstructions(a)).toContain("formal proof");expect(composeInstructions(a)).toContain("assuming");expect(composeInstructions(a)).toContain("Be precise")})
 it("records an exact clone parent revision without sharing mutable config",()=>{const original=createBuild("capybara-sage","Sage");const equipped=equipSkill(original.config,"proof-scaffolding");if(!equipped.ok)throw Error(equipped.reason);const saved=saveBuildEdit(original,{name:"Proof sage",config:equipped.config});const child=cloneBuild(saved);expect(child.parentId).toBe(saved.id);expect(child.parentVersion).toBe(2);child.config.skillIds.push("socratic-inquiry");expect(saved.config.skillIds).toEqual(["proof-scaffolding"]);expect(saved.revisions[0].config.skillIds).toEqual([])})
 it("round trips the full export and rejects malformed or invalid imported capabilities",()=>{const b=createBuild("capybara-sage","Sage");expect(importBuild(exportBuild(b))).toEqual(b);const data=JSON.parse(exportBuild(b));data.build.config.toolIds=["arbitrary-execution"];expect(()=>importBuild(JSON.stringify(data))).toThrow("No executable tools");data.build.config.toolIds=[];data.build.revisions=[{}];expect(()=>importBuild(JSON.stringify(data))).toThrow("not a valid")})
 it("rejects locked equipment and self-referencing imported ancestry",()=>{const b=createBuild("capybara-sage","Sage");expect(equipSkill(b.config,"sandboxed-execution").ok).toBe(false);expect(validateBuild({...b,config:{...b.config,skillIds:["on-chain-pattern-reading"]}}).valid).toBe(false);expect(()=>importBuild(exportBuild({...b,parentId:b.id,parentVersion:1}))).toThrow("own parent")})
})
