import {describe,it,expect} from 'vitest'
import {gradePractice,gradeMission,dailyContracts,importJourney,exportJourney,type GameEvent} from '@/lib/colosseum/gameplay'
import {createBuild,saveBuildEdit,configFingerprint,validateBuild} from '@/lib/colosseum/builds'
import {validateBattleRecord,revealedText} from '@/lib/colosseum/battle'
import {validateLocalEvidence,inputIdentity,type LocalEvidence} from '@/lib/colosseum/battle-evidence'
import {LOCAL_MODELS} from '@/lib/colosseum/models'
import {getChallenge} from '@/lib/colosseum/challenges'
import {NATIVE_REPLAYS} from '@/lib/colosseum/native-replays'

describe('real practice and educational checkers',()=>{
 it('checks the player input without producing a model identity',()=>{expect(gradePractice('the-first-sigil','297').correct).toBe(true);expect(gradePractice('the-first-sigil','296').correct).toBe(false);expect(gradePractice('labyrinth-of-sequences','Sage').correct).toBe(true);expect(()=>gradePractice('the-oracles-eye','1')).toThrow('deterministic checker')})
 it('grades decimals, mint mismatch, absent owners and source provenance independently',()=>{expect(gradeMission('supply','1000.0')).toBe(true);expect(gradeMission('supply','1e3')).toBe(false);expect(gradeMission('mint','same')).toBe(false);expect(gradeMission('mint','different')).toBe(true);expect(gradeMission('holders','two')).toBe(false);expect(gradeMission('holders','unknown')).toBe(true);expect(gradeMission('source','live')).toBe(false);expect(gradeMission('source','docs')).toBe(true)})
 it('daily contracts use explicit version, day and eligible subjects rather than button count',()=>{const now=Date.parse('2026-10-08T12:00:00Z'),c=dailyContracts([],now);const wrong:GameEvent={id:'wrong',type:'challenge_started',subject:c.challenge.id,title:'Attempted',at:now};expect(dailyContracts([wrong],now).items[0].done).toBe(false);expect(dailyContracts([{...wrong,id:'done',type:'practice_completed'}],now).items[0].done).toBe(true);expect(dailyContracts([{...wrong,id:'yesterday',at:now-86400000,type:'practice_completed'}],now).items[0].done).toBe(false);expect(c.version).toBe(1)})
 it('imports personal progress without granting duplicate event IDs or accepting unknown types',()=>{const e:GameEvent={id:'one',type:'mission_completed',subject:'supply',title:'Supply',at:1};expect(importJourney(exportJourney([e,e]))).toHaveLength(1);expect(()=>importJourney(JSON.stringify({format:'colosseum-journey',version:1,events:[{...e,type:'model_intelligence_increased'}]}))).toThrow()})
})

describe('build identity and recovered battle integrity',()=>{
 it('retains socket movement on save without pretending instructions changed',()=>{const b=createBuild('capybara-sage','Socket experiment');b.config.skillIds=['proof-scaffolding'];b.config.equipmentSlots=['proof-scaffolding',null,null];const next={...b.config,equipmentSlots:[null,null,'proof-scaffolding']};const saved=saveBuildEdit(b,{name:b.name,config:next},{now:()=>b.updatedAt+1});expect(saved.version).toBe(b.version);expect(saved.config.equipmentSlots).toEqual(next.equipmentSlots);expect(configFingerprint(saved.config)).toBe(configFingerprint(b.config))})
 it('rejects an imported visual loadout that hides or duplicates actual instructions',()=>{const b=createBuild('capybara-sage','Misleading sockets');b.config.skillIds=['proof-scaffolding'];b.config.equipmentSlots=['socratic-inquiry',null,null];expect(validateBuild(b).valid).toBe(false);b.config.equipmentSlots=['proof-scaffolding','proof-scaffolding',null];expect(validateBuild(b).valid).toBe(false)})
 it('refuses invented local provenance and unsafe recording links',()=>{const base={mode:'local-ai' as const,contenderId:'capybara-sage',challengeTitle:'Test',prompt:'Test',answer:'Captured',checker:'Test',model:'Exact identity'};expect(validateBattleRecord(base).ok).toBe(false);expect(validateBattleRecord({...base,startedByVisitor:true}).ok).toBe(true);expect(validateBattleRecord({...base,mode:'recorded',recordedAt:'2026-10-08T12:00:00Z',evidenceHref:'javascript:alert(1)'}).ok).toBe(false);expect(revealedText('Actual 🧠 output',999,0)).toBe('Actual 🧠 output')})
 it('fresh CPU captures retain the incorrect-format result and are recordings',()=>{expect(NATIVE_REPLAYS).toHaveLength(2);expect(NATIVE_REPLAYS.every(r=>r.record.mode==='recorded'&&validateBattleRecord(r.record).ok)).toBe(true);expect(NATIVE_REPLAYS.find(r=>r.entry.model==='qwen2.5-0.5b-q8')?.check.passed).toBe(false)})
})

function evidence():LocalEvidence{const model=LOCAL_MODELS[2],c=getChallenge('the-first-sigil')!;return {id:'test-fixture-not-public',mode:'local-ai',contenderId:model.contenderId,modelId:model.modelId,modelRevision:model.revision,runtime:'Transformers.js 4.3.1 / ONNX WASM CPU',challengeId:c.id,challengeVersion:c.version??1,prompt:`${c.task!.prompt}\n\n${c.task!.instructions}`,inputIdentity:inputIdentity(`${c.task!.prompt}\n\n${c.task!.instructions}`,'fixture'),buildId:null,buildFingerprint:'fixture',instructions:'fixture',parameters:{temperature:0,maxTokens:128},startedAt:1,finishedAt:2,latencyMs:1,output:'ANSWER: 8',tokens:3,status:'completed',correct:false,extracted:'8',provenance:'visitor-device; client-controlled; not independently attested',events:[]}}
describe('on-device evidence revalidation',()=>{
 it('rejects forged verdicts, drifted challenge inputs and wrong artifact revisions',()=>{const e=evidence();expect(validateLocalEvidence(e).correct).toBe(false);expect(()=>validateLocalEvidence({...e,correct:true})).toThrow('verdict');expect(()=>validateLocalEvidence({...e,prompt:'Changed prompt'})).toThrow('input');expect(()=>validateLocalEvidence({...e,modelRevision:'main'})).toThrow('revision');expect(()=>validateLocalEvidence({...e,instructions:'Changed'})).toThrow('hash')})
 it('errors and cancellations cannot be scored',()=>{expect(()=>validateLocalEvidence({...evidence(),status:'failed',correct:true})).toThrow('score');expect(validateLocalEvidence({...evidence(),status:'cancelled',correct:null,extracted:null,error:'cancelled'}).correct).toBeNull()})
})
