import {test,expect,type Page} from '@playwright/test'
async function workshop(page:Page,name='Journey build'){await page.goto('/workshop');await expect(page.getByLabel('Champion name')).toBeVisible();await page.getByLabel('Champion name').fill(name)}
async function equip(page:Page,id:string,slot:number){await page.locator(`[data-skill="${id}"]`).getByRole('button',{name:'Select relic',exact:true}).click();await page.getByRole('button',{name:new RegExp(`^Equipment slot ${slot}`)}).click()}
async function save(page:Page){await page.getByRole('button',{name:'Save build',exact:true}).click();await expect(page.locator('.feedback')).toContainText('Saved revision')}
test.beforeEach(async({page})=>{page.on('dialog',d=>d.accept())})

test('complete model/build/skill/mutation/battle/mission/journal/dispatch/export journey without paid requests',async({page})=>{
 const api:string[]=[],modelRequests:string[]=[];page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/'))api.push(r.url());if(u.hostname==='huggingface.co'||u.hostname.includes('ai-gateway'))modelRequests.push(r.url())})
 await page.goto('/');await expect(page.getByRole('heading',{name:'Qwen3 0.6B',exact:true})).toBeVisible();await expect(page.locator('.active-build-marker')).toContainText('Qwen3 0.6B')
 await page.getByLabel('Champion selection').focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('heading',{name:'Claude · Showcase',exact:true})).toBeVisible();await expect(page.locator('.active-build-marker')).toContainText('Qwen3 0.6B');await page.getByRole('button',{name:'Choose this model',exact:true}).click();await expect(page.locator('.active-build-marker')).toContainText('Claude · Showcase')
 await page.goto('/contenders');await page.getByLabel('Direct model selection').selectOption('small-spark');await page.getByRole('button',{name:'Confirm model selection'}).click();await page.getByRole('link',{name:'Prepare / enter challenge'}).click();await expect(page.locator('.active-build-marker')).toContainText('SmolLM2 135M')
 await workshop(page);await equip(page,'proof-scaffolding',1);await save(page);await page.reload();await expect(page.getByLabel('Champion name')).toHaveValue('Journey build');await expect(page.getByLabel('Equipped abilities')).toContainText('Proof Scaffolding')
 await page.goto('/skills');await page.getByRole('button',{name:/Socratic Inquiry/}).click();await page.getByRole('button',{name:'Equip ability'}).click();await page.getByRole('button',{name:'Save build',exact:true}).click();await expect(page.locator('.feedback')).toContainText('Saved revision v2');await page.goto('/workshop');await expect(page.getByLabel('Equipped abilities')).toContainText('Socratic Inquiry')
 await page.getByRole('link',{name:'Create mutation',exact:true}).click();await page.getByRole('button',{name:'Clone a variant'}).click();await page.getByLabel('Variant name').fill('   ');await expect(page.getByRole('button',{name:'Seal mutation'})).toBeDisabled();await page.getByLabel('Variant name').fill('Journey variant');await page.getByRole('button',{name:'Fermi Estimation +',exact:true}).click();await page.getByRole('button',{name:'Seal mutation',exact:true}).click();await expect(page.locator('.feedback')).toContainText('Mutation sealed');await page.getByRole('link',{name:'Inspect ancestry'}).click();await expect(page.locator('.lineage-node.child')).toContainText('Parent: Journey build at v2');await expect(page.locator('.lineage-node.child')).toContainText('+ Fermi Estimation')
 await page.goto('/');await page.getByLabel('Your answer').fill('297');await page.getByRole('button',{name:'Grade my answer'}).click();await page.getByRole('button',{name:'Play battle'}).click();await page.getByRole('button',{name:'Pause animation'}).click();const phase=await page.locator('.bs').getAttribute('data-phase');await page.waitForTimeout(250);expect(await page.locator('.bs').getAttribute('data-phase')).toBe(phase);await page.getByRole('button',{name:'Resume animation'}).click();await page.getByRole('button',{name:'Skip to result'}).click();await expect(page.locator('.bs-evidence')).toContainText('297');await expect(page.locator('.bs')).toHaveAttribute('data-mode','practice')
 await page.goto('/leaderboards');await expect(page.getByText('Your journey · personal',{exact:false})).toBeVisible();await expect(page.getByText('Mutation sealed',{exact:true})).toBeVisible();await page.goto('/solana');for(const answer of ['1000','different','unknown','docs']){const input=page.getByLabel('Mission answer');if(await input.evaluate(el=>el.tagName)==='INPUT')await input.fill(answer);else await input.selectOption(answer);await page.getByRole('button',{name:'Check finding',exact:true}).click();await expect(page.getByText('Finding accepted.',{exact:true})).toBeVisible();const next=page.getByRole('button',{name:'Enter next mission →'});if(await next.count())await next.click()}
 await page.getByRole('link',{name:'Record of your expedition →'}).click();await expect(page.locator('.journey-milestones')).toContainText('4');await expect(page.locator('.journal-timeline')).toContainText('The Evidence Archive completed');await expect(page.getByLabel('Daily contracts')).toContainText('Completed locally')
 await page.goto('/dispatch');await expect(page.getByRole('heading',{name:'From the notice board.'})).toBeVisible();await page.getByRole('button',{name:'The Forge now shares its loadout'}).click();await expect(page.locator('.dispatch-article')).toContainText('components/colosseum/equipment-forge.tsx');await page.getByLabel('Dispatch category').selectOption('NEW CONTENDERS');await expect(page.getByText('No newly verified contender announcement',{exact:false})).toBeVisible()
 await page.goto('/workshop');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export build'}).click();expect((await download).suggestedFilename()).toBe('colosseum-champion.json');expect(api).toEqual([]);expect(modelRequests).toEqual([])
})

test('real pointer dragging can equip, replace, move, remove and undo at laptop height',async({page})=>{
 await page.setViewportSize({width:1366,height:768});await workshop(page,'Drag experiment');const proof=page.getByRole('button',{name:'Drag Proof Scaffolding',exact:true}),slot1=page.getByRole('button',{name:'Equipment slot 1',exact:true});await proof.scrollIntoViewIfNeeded();const source=await proof.boundingBox(),target=await slot1.boundingBox();expect(source!.y+source!.height).toBeLessThan(768);expect(target!.y+target!.height).toBeLessThan(768);await page.mouse.move(source!.x+source!.width/2,source!.y+source!.height/2);await page.mouse.down();await page.mouse.move(target!.x+target!.width/2,target!.y+target!.height/2,{steps:12});await expect(slot1.locator('..')).toHaveClass(/over/);await page.mouse.up();await expect(page.getByRole('button',{name:'Equipment slot 1: Proof Scaffolding'})).toBeVisible()
 await equip(page,'socratic-inquiry',1);await expect(page.getByRole('button',{name:'Equipment slot 1: Socratic Inquiry'})).toBeVisible();await expect(page.getByLabel('Equipped abilities')).not.toContainText('Proof Scaffolding');const move=page.getByRole('button',{name:'Move Socratic Inquiry',exact:true}),dest=page.getByRole('button',{name:'Equipment slot 3',exact:true});const a=await move.boundingBox(),b=await dest.boundingBox();await page.mouse.move(a!.x+a!.width/2,a!.y+a!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2,{steps:12});await expect(dest.locator('..')).toHaveClass(/over/);await page.mouse.up();await expect(page.getByRole('button',{name:'Equipment slot 3: Socratic Inquiry'})).toBeVisible();await save(page);await page.reload();await expect(page.getByRole('button',{name:'Equipment slot 3: Socratic Inquiry'})).toBeVisible();await page.getByRole('button',{name:'Remove Socratic Inquiry',exact:true}).click();await expect(page.getByLabel('Equipped abilities')).not.toContainText('Socratic Inquiry');await page.getByRole('button',{name:'Undo equipment'}).click();await expect(page.getByLabel('Equipped abilities')).toContainText('Socratic Inquiry');await page.screenshot({path:'.validation/phase4/forge-laptop.png'})
})

test('keyboard and touch equipment, reduced motion and world navigation work on mobile',async({page,context})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await workshop(page,'Keyboard experiment');const pick=page.locator('[data-skill="proof-scaffolding"]').getByRole('button',{name:'Select relic',exact:true});await pick.focus();await page.keyboard.press('Enter');const slot=page.getByRole('button',{name:'Equipment slot 2',exact:true});await slot.focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Equipped abilities')).toContainText('Proof Scaffolding');await save(page);await page.getByText('World map',{exact:true}).click();await expect(page.getByRole('navigation',{name:'World destinations'}).getByRole('link',{name:'Ledger Island'})).toBeVisible();await page.getByRole('navigation',{name:'World destinations'}).getByRole('link',{name:'Ledger Island'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.validation/phase4/ledger-mobile.png'})
 const touch=await context.browser()!.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const p=await touch.newPage();await p.goto(new URL('/workshop',page.url()).href);await p.getByLabel('Champion name').waitFor();await p.locator('[data-skill="ledger-interpretation"]').getByRole('button',{name:'Select relic',exact:true}).tap();await p.getByRole('button',{name:'Equipment slot 1',exact:true}).tap();await expect(p.getByLabel('Equipped abilities')).toContainText('Ledger Interpretation');await touch.close()
})

test('cross-tab saves reject stale overwrite while preserving the unsaved draft',async({page,context})=>{
 await workshop(page,'Shared original');await save(page);const other=await context.newPage();other.on('dialog',d=>d.accept());await other.goto(new URL('/workshop',page.url()).href);await expect(other.getByLabel('Champion name')).toHaveValue('Shared original');await other.getByLabel('Champion name').fill('Other tab saved');await other.getByRole('button',{name:'Save build',exact:true}).click();await expect(other.locator('.feedback')).toContainText('Saved revision');await expect(page.locator('.feedback')).toContainText('Another tab');await page.getByLabel('Champion name').fill('Stale draft retained');await page.getByRole('button',{name:'Save build',exact:true}).click();await expect(page.locator('.feedback')).toContainText('newer revision');await expect(page.getByLabel('Champion name')).toHaveValue('Stale draft retained');await other.reload();await expect(other.getByLabel('Champion name')).toHaveValue('Other tab saved')
})

test('quota and unavailable storage permit a usable export instead of silently losing work',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Test-only unavailable storage','SecurityError')}});Storage.prototype.setItem=function(){throw new DOMException('Test-only full storage','QuotaExceededError')}});await workshop(page,'Session retained');await equip(page,'proof-scaffolding',1);await page.getByRole('button',{name:'Save build',exact:true}).click();await expect(page.locator('.feedback')).toContainText('storage');await expect(page.getByLabel('Champion name')).toHaveValue('Session retained');const d=page.waitForEvent('download');await page.getByRole('button',{name:'Export build'}).click();expect((await d).suggestedFilename()).toBe('colosseum-champion.json')
})

test('failed and cancelled downloads never become a playable result or success animation',async({page})=>{
 await page.route('https://huggingface.co/**',r=>r.abort('failed'));await page.goto('/contenders');await page.getByLabel('Direct model selection').selectOption('small-spark');await page.getByRole('button',{name:'Confirm model selection'}).click();await page.getByRole('link',{name:'Prepare / enter challenge'}).click();await page.getByRole('button',{name:'Local AI execution',exact:true}).click();await expect(page.getByRole('button',{name:'Prepare model'})).toBeDisabled();await page.getByRole('checkbox',{name:'I consent to download this model to my device.',exact:true}).check();await page.getByRole('button',{name:'Prepare model',exact:true}).click();await expect(page.locator('.download-consent [role="status"]')).toContainText(/failed|Unable|fetch|error|local/i);await expect(page.getByRole('button',{name:'Start local battle'})).toBeDisabled();expect(await page.locator('.bs[data-outcome="correct"]').count()).toBe(0)
 await page.unroute('https://huggingface.co/**');await page.route('https://huggingface.co/**',async r=>{await new Promise(resolve=>setTimeout(resolve,2500));await r.abort('failed')});await page.getByRole('button',{name:'Prepare model',exact:true}).click();await page.getByRole('button',{name:'Cancel execution'}).click();await expect(page.locator('.download-consent [role="status"]')).toContainText('Cancelled');await expect(page.getByRole('button',{name:'Start local battle'})).toBeDisabled()
})

test('authentic replay retains its original output and failed final-answer format',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Recorded replay',exact:true}).click();await page.getByRole('button',{name:'Replay Qwen2.5 0.5B · free CPU',exact:true}).click();await page.getByRole('button',{name:'Play battle'}).click();await page.getByRole('button',{name:'Skip to result'}).click();await expect(page.locator('.bs')).toHaveAttribute('data-mode','recorded');await expect(page.locator('.bs')).toHaveAttribute('data-outcome','incorrect');await expect(page.locator('.bs-evidence')).toContainText('Therefore, the final answer is 244.');await expect(page.locator('.bs-evidence')).toContainText('math.warmup v1')
})

for(const size of [{width:1920,height:1080},{width:1440,height:900},{width:1366,height:768},{width:390,height:844}])test(`all world destinations remain usable at ${size.width}×${size.height}`,async({page})=>{
 await page.setViewportSize(size);await page.emulateMedia({reducedMotion:'reduce'});for(const route of ['/','/workshop','/skills','/mutation-lab','/solana','/leaderboards','/battle-archive','/lineage','/dispatch','/journal','/contenders','/developers']){await page.goto(route);await expect(page.locator('h1').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route).toBe(true)}
 await page.getByLabel('Interface settings').click();await page.getByLabel('Visual effects').selectOption('low');expect(await page.locator('html').getAttribute('data-effects')).toBe('low')
})
