import {z} from "zod"
import {validateBuild,BUILD_LIMITS,type AgentBuild} from "./builds"
const DB_NAME="colosseum-workshop",STORE_NAME="builds",VERSION=1
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==="undefined"){reject(new Error("Browser storage is unavailable."));return}const r=indexedDB.open(DB_NAME,VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE_NAME))r.result.createObjectStore(STORE_NAME,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error("Close another open Workshop tab and retry."))})}
export async function listBuilds():Promise<AgentBuild[]>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,"readonly"),r=tx.objectStore(STORE_NAME).getAll();tx.oncomplete=()=>{db.close();resolve((r.result as AgentBuild[]).sort((a,b)=>b.updatedAt-a.updatedAt))};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error??new Error("Read aborted."))}})}
async function write(action:(store:IDBObjectStore)=>void){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE_NAME,"readwrite");action(tx.objectStore(STORE_NAME));tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error??new Error("Save aborted."))}})}
export async function saveBuild(build:AgentBuild){return write(store=>{store.put(build)})}
export async function deleteBuild(id:string){return write(store=>{store.delete(id)})}
export function exportBuild(build:AgentBuild){return JSON.stringify({format:"colosseum-build",version:1,build},null,2)}
const id=z.string().min(1).max(100),timestamp=z.number().finite().nonnegative(),version=z.number().int().positive()
const config=z.object({contenderId:id,modelId:z.string().max(200).nullable(),runtime:z.string().min(1).max(80),soul:z.string().max(BUILD_LIMITS.maxSoulLength),skillIds:z.array(id).max(4),toolIds:z.array(id).max(4),knowledgeSources:z.array(id).max(4)})
const buildSchema=z.object({id,name:z.string().min(1).max(48),config,version,parentId:id.nullable(),parentVersion:version.nullable(),createdAt:timestamp,updatedAt:timestamp,revisions:z.array(z.object({version,savedAt:timestamp,config})).max(20)})
export function importBuild(text:string):AgentBuild{if(text.length>100000)throw new Error("Build file is too large.");const parsed=z.object({format:z.literal("colosseum-build"),version:z.literal(1),build:buildSchema}).safeParse(JSON.parse(text));if(!parsed.success)throw new Error("That file is not a valid COLOSSEUM v1 build.");const build=parsed.data.build;const validation=validateBuild(build);if(!validation.valid)throw new Error(validation.issues.filter(v=>v.severity==="error").map(v=>v.message).join(" "));if(build.parentId===build.id)throw new Error("A build cannot be its own parent.");if((build.parentId===null)!==(build.parentVersion===null))throw new Error("Parent identity and revision must be recorded together.");return build}
