"use client"
import {createContext,useContext,useRef,useState,useEffect,type ReactNode} from "react"
import {LocalRuntime,supportedDevice,type DeviceStatus} from "./local-runtime"
import type {LocalModel} from "./models"
function useDeviceState(){
 const runtime=useRef<LocalRuntime|null>(null),abort=useRef<AbortController|null>(null),active=useRef<string|null>(null),busyRef=useRef(false)
 const [statuses,setStatuses]=useState<Record<string,DeviceStatus>>({}),[busy,setBusy]=useState(false)
 useEffect(()=>()=>{abort.current?.abort();runtime.current?.cancel()},[])
 function status(id:string,next:DeviceStatus){setStatuses(old=>({...old,[id]:{...old[id],...next}}))}
 function cancel(){abort.current?.abort();if(active.current)status(active.current,{state:'cancelled',detail:'Cancelled by visitor. Start again to initialize the model.'});runtime.current?.cancel();active.current=null;busyRef.current=false;setBusy(false)}
 async function prepare(model:LocalModel,consented:boolean){if(!consented)throw Error("Explicit download consent is required.");if(busyRef.current)throw Error("Another device action is running.");if(!supportedDevice()){status(model.contenderId,{state:'unsupported',detail:'WebAssembly and Web Workers are required. Use deterministic practice.'});return false}busyRef.current=true;setBusy(true);abort.current=new AbortController();if(active.current&&active.current!==model.contenderId)status(active.current,{state:'untested',detail:'Runtime released to prepare another model. Previous evidence remains available.'});runtime.current??=new LocalRuntime();active.current=model.contenderId;try{await runtime.current.load(model,abort.current.signal,s=>status(model.contenderId,s));return true}catch(e){status(model.contenderId,{state:abort.current.signal.aborted?'cancelled':'failed',detail:e instanceof Error?e.message:'Initialization failed',error:String(e)});return false}finally{busyRef.current=false;setBusy(false)}}
 async function generate(model:LocalModel,messages:{role:string;content:string}[],maxTokens:number,onDelta:(s:string)=>void){if(busyRef.current)throw Error("Another device action is running.");if(active.current!==model.contenderId)throw Error('Prepare this model first.');busyRef.current=true;setBusy(true);abort.current=new AbortController();status(model.contenderId,{state:'generating',detail:'Generating actual model output on this device…'});try{const result=await runtime.current!.generate(model,messages,maxTokens,abort.current.signal,onDelta);status(model.contenderId,{state:'ready',detail:'Output captured; deterministic judging follows.',lastGenerationMs:result.latencyMs});return result}catch(e){status(model.contenderId,{state:abort.current.signal.aborted?'cancelled':'failed',detail:e instanceof Error?e.message:'Generation failed',error:String(e)});throw e}finally{busyRef.current=false;setBusy(false)}}
 return {statuses,busy,prepare,generate,cancel,verify:(id:string)=>status(id,{state:'verified',detail:'PLAYABLE — VERIFIED: a genuine generation completed and was deterministically evaluated in this session.',verifiedAt:Date.now()}),ready:(id:string)=>active.current===id&&['ready','verified'].includes(statuses[id]?.state??'')}
}
const DeviceContext=createContext<ReturnType<typeof useDeviceState>|null>(null)
export function DeviceProvider({children}:{children:ReactNode}){const value=useDeviceState();return <DeviceContext.Provider value={value}>{children}</DeviceContext.Provider>}
export function useDevice(){const value=useContext(DeviceContext);if(!value)throw Error('DeviceProvider missing');return value}
