"use client"
import {useEffect,useState} from "react"
import Link from "next/link"
import entries from "@/data/world-dispatch.json"
import {useGame} from "@/lib/colosseum/game-store"
import {useDevice} from "@/lib/colosseum/device-store"
export function DispatchPreview(){return <section className="dispatch-preview"><p className="eyebrow">THE WORLD DISPATCH</p><h2>A world that grows through real work.</h2>{entries.slice(0,2).map(e=><Link key={e.id} href={`/dispatch?notice=${e.id}`}><small>{e.type} · {e.publishedAt}</small><strong>{e.title}</strong></Link>)}<Link href="/dispatch" className="text-link">Read the notice board →</Link></section>}
export function DispatchBoard(){const game=useGame(),device=useDevice(),[category,setCategory]=useState('all'),[read,setRead]=useState<string[]>([]),[track,setTrack]=useState(false),[open,setOpen]=useState<string|null>(null)
 useEffect(()=>{setOpen(new URLSearchParams(location.search).get('notice'));try{const data=JSON.parse(localStorage.getItem('colosseum:dispatch:v1')??'{}');setTrack(data.enabled===true);setRead(Array.isArray(data.ids)?data.ids:[])}catch{}},[])
 function mark(id:string){setOpen(id);history.replaceState(null,'',`?notice=${encodeURIComponent(id)}`);if(track){const ids=[...new Set([...read,id])];setRead(ids);try{localStorage.setItem('colosseum:dispatch:v1',JSON.stringify({enabled:track,ids}))}catch{game.setMessage('Read tracking could not be saved.')}}}
 return <div className="page-shell"><header className="page-heading"><p className="eyebrow">THE WORLD DISPATCH</p><h1>From the notice board.</h1><p>Repository-maintained announcements and clearly marked personal activity. No fabricated players or social trends.</p></header><div className="button-row"><label>Bulletin category<select aria-label="Dispatch category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All published updates</option>{['NEW CONTENDERS','ARENA CHANGES','NEW RELICS','RESEARCH DISPATCHES'].map(c=><option key={c}>{c}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={track} onChange={e=>{setTrack(e.target.checked);try{localStorage.setItem('colosseum:dispatch:v1',JSON.stringify({enabled:e.target.checked,ids:read}))}catch{game.setMessage('Read tracking unavailable.')}}}/>Track unread notices locally</label></div><div className="dispatch-board">{entries.filter(e=>category==='all'||e.type===category).map(e=><article key={e.id} className="dispatch-notice"><small>{e.type} · {e.publishedAt}{track&&!read.includes(e.id)?' · UNREAD':''}</small><h2><button onClick={()=>mark(e.id)}>{e.title}</button></h2><p>{e.summary}</p>{open===e.id&&<div className="dispatch-article"><p>{e.details}</p><p className="compact-note">Status: {e.verificationStatus}</p><code>{e.changeReference}</code><div className="button-row"><Link href={e.route} className="action">Explore update</Link><a href={e.source} className="text-link">Source / change reference ↗</a></div></div>}</article>)}</div>{category==='NEW CONTENDERS'&&<p className="empty-state">No newly verified contender announcement has been published. Candidate artifacts remain separate from actual device verification.</p>}<section className="dispatch-local"><h2>Your activity</h2><p className="eyebrow">PERSONAL · THIS BROWSER</p>{game.events.slice(0,4).map(e=><p key={e.id}>{e.title} · {new Date(e.at).toLocaleString()}</p>)}{!game.events.length&&<p>No local activity yet.</p>}<Link href="/journal" className="text-link">Open adventure journal →</Link></section><section className="dispatch-local"><h2>World status</h2><p>Hosted public inference: disabled by default. Local models initialize only after explicit download consent.</p>{Object.entries(device.statuses).map(([id,s])=><p key={id}>{id}: {s.state} · {s.detail}</p>)}</section><p className="feedback" role="status">{game.message}</p></div>
}
