"use client"
import {useGame} from "@/lib/colosseum/game-store"
import {modelTitle} from "@/lib/colosseum/models"
import {useState} from "react"
import Link from "next/link"
import {CONTENDERS} from "@/lib/colosseum/characters"
import {lineageRows} from "@/lib/colosseum/lineage"
import {describeConfigDiff} from "@/lib/colosseum/builds"
import {ContenderPortrait} from "./contender-portrait"
export function LineageView(){const game=useGame();const [family,setFamily]=useState(CONTENDERS[0].family)
 const builds=game.builds;
 const families=[...new Set(CONTENDERS.map(c=>c.family))],champion=CONTENDERS.find(c=>c.family===family)??CONTENDERS[0]
 return <div className="page-shell"><header className="page-heading"><p className="eyebrow">FACTIONS & REAL ANCESTRY</p><h1>Every branch has a beginning.</h1><p>Model families describe technical identity. Champion lineage describes your saved builds, clone parents, and configuration revisions.</p></header><div className="family-gallery" role="group" aria-label="Model families">{families.map(f=>{const c=CONTENDERS.find(x=>x.family===f)!;return <button className="family-tile tactile" key={f} aria-pressed={f===family} onClick={()=>setFamily(f)}><ContenderPortrait contender={c} size="lg"/><span>{f}</span></button>})}</div><div className="selected-champion-strip"><ContenderPortrait contender={champion}/><div><h2>{modelTitle(champion)}</h2><p className="text-xs break-all">{champion.modelId??"No model configured"}</p><p className="text-xs mt-2">Fictional identity · no family performance implied</p></div></div><h2 className="font-display text-3xl mt-10">Champion lineage</h2>{!builds.length?<div className="empty-state mt-5"><p className="mb-4">No saved ancestry exists in this browser.</p><Link className="action primary" href="/workshop">Create your first branch</Link></div>:<div className="lineage-tree">{lineageRows(builds).map(({build:b,depth})=>{const parent=builds.find(p=>p.id===b.parentId),parentConfig=parent?(parent.version===b.parentVersion?parent.config:parent.revisions.find(r=>r.version===b.parentVersion)?.config):null;const c=CONTENDERS.find(x=>x.id===b.config.contenderId);return <article key={b.id} className={`lineage-node ${b.parentId?"child":""}`} style={{marginLeft:Math.min(depth,4)*20}}>{c&&<ContenderPortrait contender={c} size="sm"/>}<div><h3>{b.name}</h3><small>v{b.version} · {b.config.skillIds.length} abilities · NOT YET TESTED</small><p className="text-xs mt-2">{b.parentId?`↳ Parent: ${parent?.name??b.parentId} at v${b.parentVersion}`:"Root build · no parent"}</p>{parentConfig&&<p className="text-xs mt-1">{describeConfigDiff(parentConfig,b.config).join(" · ")||"Same configuration as parent"}</p>}<Link className="text-xs underline mt-2 inline-block" href={`/workshop?build=${encodeURIComponent(b.id)}`}>Inspect this build</Link></div><details><summary className="text-xs">{b.revisions.length} saved revisions</summary>{b.revisions.map(r=><details className="mt-2 text-xs" key={r.version}><summary>Revision v{r.version}</summary><pre>{JSON.stringify(r.config,null,2)}</pre></details>)}</details></article>})}</div>}<p className="notice">No evaluation is tied to these build fingerprints. Family membership and configuration changes are not measured improvements.</p><p className="feedback" role="status">{game.message}</p></div>
}
