"use client"
import { useEffect, useState } from "react"
import { Settings2 } from "lucide-react"
export function WorldSettings() {
 const [sound,setSound]=useState(false),[motion,setMotion]=useState("system"),[effects,setEffects]=useState("standard")
 useEffect(()=>{try {const s=JSON.parse(localStorage.getItem("colosseum:senses:v1")||"{}");setSound(s.sound===true);setMotion(s.motion||"system");setEffects(s.effects||"standard")}catch{}},[])
 useEffect(()=>{document.documentElement.dataset.motion=motion;document.documentElement.dataset.effects=effects;try{localStorage.setItem("colosseum:senses:v1",JSON.stringify({sound,motion,effects}))}catch{}},[sound,motion,effects])
 useEffect(()=>{if(!sound)return;let ctx:AudioContext|null=null;const click=(event:MouseEvent)=>{if(!(event.target as HTMLElement).closest("button,a"))return;try{ctx??=new AudioContext();void ctx.resume();const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type="sine";oscillator.frequency.setValueAtTime(760,ctx.currentTime);oscillator.frequency.exponentialRampToValueAtTime(1120,ctx.currentTime+.06);gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.09);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+.1)}catch{}};document.addEventListener("click",click);return()=>{document.removeEventListener("click",click);void ctx?.close()}},[sound])
 return <details className="world-settings"><summary aria-label="Interface settings"><Settings2 size={18}/><span className="sr-only">Interface settings</span></summary><div className="settings-sheet"><strong>Make yourself at home</strong><label><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> Interface sounds</label><label>Motion<select value={motion} onChange={e=>setMotion(e.target.value)}><option value="system">Device preference</option><option value="full">Full</option><option value="reduced">Reduced</option></select></label><label>Visual effects<select value={effects} onChange={e=>setEffects(e.target.value)}><option value="standard">Standard</option><option value="low">Low</option></select></label><small>Sounds start only after you enable them.</small></div></details>
}
