"use client"
import {useEffect,useRef,useState} from "react"
import Link from "next/link"
import {useGame} from "@/lib/colosseum/game-store"
import {CONTENDERS} from "@/lib/colosseum/characters"
import {skillsByWing,getSkill} from "@/lib/colosseum/skills"
import {isSkillCompatible,composeInstructions} from "@/lib/colosseum/builds"
import {modelTitle} from "@/lib/colosseum/models"
import {RelicIcon,wingColor} from "./skill-art"
export function SkillHall(){
 const game=useGame(),[selected,setSelected]=useState('proof-scaffolding'),map=useRef<HTMLDivElement>(null)
 useEffect(()=>{setSelected(new URLSearchParams(location.search).get('skill')??sessionStorage.getItem('colosseum:skill-node')??'proof-scaffolding')},[])
 const skill=getSkill(selected),champion=CONTENDERS.find(c=>c.id===game.draft?.config.contenderId)??CONTENDERS[0],compatible=skill?isSkillCompatible(skill,champion):false
 function choose(id:string){setSelected(id);try{sessionStorage.setItem('colosseum:skill-node',id)}catch{}history.replaceState(null,'',`?skill=${encodeURIComponent(id)}`)}
 return <div className="page-shell"><header className="page-heading"><p className="eyebrow">THE CAPABILITY CONSTELLATION</p><h1>The Skill Hall</h1><p>Follow a constellation. Inspect the exact ability. Shape your next experiment.</p></header><div className="constellation-toolbar"><strong>{modelTitle(champion)}</strong><label>Active build<select aria-label="Equip to saved build" value={game.draft?.id??''} onChange={e=>{const b=game.builds.find(b=>b.id===e.target.value);if(b)game.select(b)}}><option value={game.draft?.id??''}>{game.draft?.name??'Loading build…'}</option>{game.builds.filter(b=>b.id!==game.draft?.id).map(b=><option key={b.id} value={b.id}>{b.name} · v{b.version}</option>)}</select></label><button className="action" aria-label="Pan constellation left" onClick={()=>map.current?.scrollBy({left:-280,behavior:'smooth'})}>←</button><button className="action" aria-label="Pan constellation right" onClick={()=>map.current?.scrollBy({left:280,behavior:'smooth'})}>→</button></div><div className="ability-explorer"><div ref={map} className="ability-map" tabIndex={0} aria-label="Capability constellation"><div className="constellation-field">{Array.from(skillsByWing()).map(([wing,skills],i)=><section key={wing} className="ability-cluster" style={{gridColumn:i%4+1,gridRow:Math.floor(i/4)+1,borderColor:wingColor(wing)}}><h2>{wing}</h2><div className="constellation-path" aria-hidden/><div className="ability-nodes">{skills.map(s=><button key={s.id} className={`ability-node ${selected===s.id?'selected':''} ${game.draft?.config.skillIds.includes(s.id)?'equipped':''}`} aria-pressed={selected===s.id} onClick={()=>choose(s.id)}><RelicIcon skillId={s.id} wing={s.wing} size={60} dim={!s.available}/><span>{s.name}</span><small>{game.draft?.config.skillIds.includes(s.id)?'EQUIPPED':s.available?'Instruction relic':'OFFLINE'}</small></button>)}</div></section>)}</div></div><aside className="ability-detail" aria-label="Selected ability">{skill&&<><RelicIcon skillId={skill.id} wing={skill.wing} size={86}/><p className="eyebrow">{skill.wing}</p><h2>{skill.name}</h2><p>{skill.description}</p><p className="compact-note">{skill.available?(compatible?'Compatible with your selected model.':'Incompatible with this model family.'):skill.unavailableReason}</p><details><summary>Preview configuration effect</summary><pre>{skill.instructionPrompt??'No connected tool; cannot equip.'}</pre></details><button className="action primary" disabled={!skill.available||!compatible} onClick={()=>game.place(skill.id)}>Equip ability</button><button className="action" onClick={()=>void game.persist()}>Save build</button><Link className="text-link" href="/workshop">Inspect the complete loadout →</Link><p className="compact-note">Lines group capabilities; they do not invent prerequisites. Equipping modifies prompt text, not model weights or intelligence.</p></>}</aside></div><p className="feedback" role="status">{game.message}</p></div>
}
