"use client"
import { useEffect,useState } from "react"
import Image from "next/image"
import Link from "next/link"
import { Sparkles,Plus,Copy,Download,Save,X,BookOpen } from "lucide-react"
import { CONTENDERS } from "@/lib/colosseum/characters"
import { SKILLS,getSkill,type Skill } from "@/lib/colosseum/skills"
import { createBuild,cloneBuild,equipSkill,saveBuildEdit,unequipSkill,validateBuild,changeContender,composeInstructions,describeConfigDiff,BUILD_LIMITS,type AgentBuild } from "@/lib/colosseum/builds"
import { exportBuild,importBuild,listBuilds,saveBuild } from "@/lib/colosseum/build-store"
import { loadLastChampion } from "@/lib/colosseum/local-state"
import { downloadJson } from "@/lib/colosseum/download"
import { SkillDetails } from "./skill-details"
export function WorkshopView(){
 const [builds,setBuilds]=useState<AgentBuild[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[draft,setDraft]=useState<AgentBuild|null>(null),[message,setMessage]=useState(""),[detail,setDetail]=useState<Skill|null>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{listBuilds().then(items=>{setBuilds(items);const requested=new URLSearchParams(location.search).get("build");const chosen=items.find(b=>b.id===requested)??items[0];if(chosen){setSelectedId(chosen.id);setDraft(structuredClone(chosen))}}).catch(()=>setMessage("Browser storage is unavailable. You can configure and export a build, but saving may fail."))},[])
 const contender=CONTENDERS.find(c=>c.id===draft?.config.contenderId)??CONTENDERS[0],validation=draft?validateBuild(draft):null
 const selected=builds.find(b=>b.id===selectedId)
 function select(build:AgentBuild){setSelectedId(build.id);setDraft(structuredClone(build));setMessage("")}
 function create(){if(builds.length>=BUILD_LIMITS.maxBuilds){setMessage("Build limit reached. Export a build before removing any.");return}const next=createBuild(loadLastChampion()??CONTENDERS[0].id,"New champion");setSelectedId(next.id);setDraft(next);setMessage("New configuration. Save it to keep it in this browser.")}
 function change(id:string){if(!draft)return;const result=changeContender(draft.config,id);setDraft({...draft,config:result.config});setMessage(result.dropped.length?`Removed incompatible skills: ${result.dropped.join(", ")}`:"")}
 function equip(id:string){if(!draft){setMessage("Create a build first.");return}const result=equipSkill(draft.config,id);if(result.ok){setDraft({...draft,config:result.config});setMessage(`${getSkill(id)?.name} equipped as instruction text. NOT YET TESTED.`)}else setMessage(result.reason)}
 function remove(id:string){if(draft)setDraft({...draft,config:unequipSkill(draft.config,id)})}
 async function persist(next:AgentBuild){setBusy(true);try{await saveBuild(next);setBuilds(items=>[next,...items.filter(b=>b.id!==next.id)]);select(next);setMessage(`Saved revision v${next.version}. NOT YET TESTED.`)}catch{setMessage("Save failed. Export this build to retain your work.")}finally{setBusy(false)}}
 function save(){if(!draft||!validation?.valid)return;const next=selected?saveBuildEdit(selected,{name:draft.name,config:draft.config}):draft;void persist(next)}
 function clone(){if(!draft)return;if(builds.length>=BUILD_LIMITS.maxBuilds){setMessage("At most 24 saved builds.");return}void persist(cloneBuild(selected??draft))}
 async function upload(file:File){try{if(file.size>100000)throw Error("Build file is too large.");const next=importBuild(await file.text());if(!builds.some(b=>b.id===next.id)&&builds.length>=BUILD_LIMITS.maxBuilds)throw Error("Build limit reached.");if(builds.some(b=>b.id===next.id))throw Error("This build already exists. Clone it instead of overwriting its history.");await persist(next)}catch(e){setMessage(e instanceof Error?e.message:"Import failed.")}}
 return <div className="page-shell"><header className="page-heading"><p className="eyebrow">THE CHAMPION FORGE</p><h1>Make a mind your own.</h1><p>Attach instruction abilities, inspect the complete configuration, and save a champion. Your equipment changes a prompt; it does not train a model.</p></header>
 <div className="forge-layout"><aside className="forge-list surface"><h2 className="font-display text-xl">Your builds</h2><button className="create-button" onClick={create}><Plus size={16} className="inline"/> New champion</button>{builds.map(b=><button key={b.id} aria-pressed={b.id===selectedId} onClick={()=>select(b)}><strong className="block text-sm">{b.name}</strong><small>v{b.version} · {b.config.skillIds.length} abilities</small></button>)}{!builds.length&&<p className="text-xs">No saved builds yet.</p>}<label className="text-xs mt-4">Import champion<input aria-label="Import champion JSON" type="file" accept="application/json" className="w-full mt-2 text-xs" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></aside>
 <section className="forge-center">{draft?<><div className="equipment-orbit"><div className="forge-portrait">{contender.portrait&&<Image src={contender.portrait} alt={contender.name} fill sizes="(max-width:900px) 80vw, 400px"/>}</div><div className="equipment-slots" aria-label="Equipped abilities">{Array.from({length:4},(_,i)=>{const skill=getSkill(draft.config.skillIds[i]);return <div key={i} className={`equipment-slot ${skill?"equipped":""}`}><Sparkles size={18}/><span>{skill?skill.name:`Ability slot ${i+1}`}</span>{skill&&<button aria-label={`Remove ${skill.name}`} onClick={()=>remove(skill.id)}><X size={14}/></button>}</div>})}</div></div>
 <div className="surface mt-4"><label className="text-xs">Champion name<input aria-label="Champion name" className="w-full mt-2" value={draft.name} maxLength={48} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="text-xs mt-4">Model vessel<select aria-label="Model vessel" className="w-full mt-2" value={contender.id} onChange={e=>change(e.target.value)}>{CONTENDERS.map(c=><option key={c.id} value={c.id}>{c.name} · {c.family}</option>)}</select></label><small className="block mt-2 break-all">{draft.config.modelId??"No runner configured"}</small><label className="text-xs mt-4">Core instructions<textarea aria-label="Core instructions" className="w-full mt-2" rows={3} maxLength={1200} value={draft.config.soul} onChange={e=>setDraft({...draft,config:{...draft.config,soul:e.target.value}})} placeholder="What should your champion pay attention to?"/></label></div></>:<div className="empty-state"><div className="forge-portrait">{contender.portrait&&<Image src={contender.portrait} alt={contender.name} fill sizes="400px"/>}</div><h2 className="font-display text-2xl">A champion awaits its equipment.</h2><button className="action primary mt-5" onClick={create}>Create build</button></div>}</section>
 <aside className="forge-inventory"><p className="eyebrow">ABILITY INVENTORY</p><p className="text-xs mb-4">Instruction modifiers are equippable. Tools and external sources remain locked.</p><div className="inventory">{SKILLS.map(s=>{const equipped=draft?.config.skillIds.includes(s.id);return <div key={s.id} className={`inventory-node ${s.available?"":"locked"}`} aria-pressed={equipped??false}><div className="flex items-center gap-2"><Sparkles size={15}/><strong>{s.name}</strong></div><small>{s.instructionPrompt?"Instruction modifier":"Locked capability"}</small><div className="flex gap-2"><button className="text-xs underline" disabled={!draft||!s.available||(!equipped&&(draft.config.skillIds.length>=4))} onClick={()=>equipped?remove(s.id):equip(s.id)}>{equipped?"Remove":"Equip"}</button><button className="text-xs underline" onClick={()=>setDetail(s)}>Details</button></div></div>})}</div></aside></div>
 {draft&&<div className="forge-footer"><p className="eyebrow">CONFIGURATION · NOT YET TESTED</p><strong>{validation?.valid?"Configuration valid":"Configuration needs attention"}</strong>{validation?.issues.map((v,i)=><p className="text-xs mt-2" key={i}>{v.message}</p>)}<div className="button-row"><button className="action primary" disabled={busy||!validation?.valid} onClick={save}><Save size={15}/>Save champion</button><button className="action" disabled={busy} onClick={clone}><Copy size={15}/>Clone saved build</button><button className="action" onClick={()=>downloadJson("colosseum-champion.json",exportBuild(draft))}><Download size={15}/>Export build</button><Link className="action" href="/mutation-lab">Create mutation</Link></div><details><summary className="text-sm"><BookOpen size={15} className="inline"/> Inspect complete instructions</summary><pre className="text-xs mt-3">{composeInstructions(draft.config)||"No instruction modifiers."}</pre><pre className="text-xs mt-3">{JSON.stringify(draft.config,null,2)}</pre></details>{selected?.revisions.length? <details className="mt-4"><summary>Revision history ({selected.revisions.length})</summary>{selected.revisions.map(r=><div key={r.version} className="notice"><strong>v{r.version}</strong><p>{describeConfigDiff(r.config,selected.config).join(" · ")||"Same configuration"}</p><details><summary>Inspect revision</summary><pre>{JSON.stringify(r.config,null,2)}</pre></details></div>)}</details>:null}<p className="notice">Public inference is off. Saving or equipping never sends a model request. No recorded evaluation is tied to this full build yet.</p></div>}
 <p className="feedback" role="status">{message}</p><SkillDetails skill={detail} onClose={()=>setDetail(null)} onEquip={draft?equip:undefined}/></div>
}
